data:
  category_csv: ./category.csv
  test_csv: ../data/test/test_input.csv
  debug: false

model:
  pretrained_model_name_or_path : './results/checkpoint-49500'

pred:
  batch_size: 64
  threshold: 1.5
  submission_csv: './results/checkpoint-49500/submission.csv'

  device: "cuda:0"
